# rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-peer-discovery
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-peer-discovery-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default        # change if using a custom service account
    namespace: default
roleRef:
  kind: Role
  name: app-peer-discovery
  apiGroup: rbac.authorization.k8s.io
